// Included after the overlay widgets, inside its UI namespace.
lemming::aim::Configuration g_aimUi{};int g_aimEditMode=0;
ImVec4 g_angleFovColor{.59f,.68f,1.f,.8f};float g_angleFovThickness=1.5f;
void drawAngleFovGeometry(const lemming::aim::assists::FovGeometry& g){
 if(!g.valid)return;auto* d=ImGui::GetBackgroundDrawList();auto size=ImGui::GetIO().DisplaySize;
 if(g.coversScreen){d->AddRect(ImVec2(2,2),ImVec2(size.x-2,size.y-2),uiColor(g_angleFovColor),0,0,g_angleFovThickness);d->AddText(ImVec2(12,40),uiColor(g_angleFovColor),"Angles FOV covers viewport");return;}
 std::array<ImVec2,128> points{};for(unsigned i=0;i<points.size();++i){float t=float(i)*6.28318530718f/points.size();points[i]={g.centerX+g.radiusX*std::cos(t),g.centerY+g.radiusY*std::sin(t)};}
 d->AddPolyline(points.data(),int(points.size()),IM_COL32(0,0,0,125),ImDrawFlags_Closed,g_angleFovThickness+2);
 d->AddPolyline(points.data(),int(points.size()),uiColor(g_angleFovColor),ImDrawFlags_Closed,g_angleFovThickness);
}
void renderAngleFov(){
 auto c=lemming::aim::configuration();if(!c.normal.enabled||!c.normal.showFov)return;
 lemming::esp::CameraMatrixCache m{};std::uintptr_t camera=0;if(!lemming::esp::detail::readCameraForPresent(m,camera)||std::fabs(m.projection.value[11])<.5f)return;
 auto size=ImGui::GetIO().DisplaySize;drawAngleFovGeometry(lemming::aim::assists::fovGeometry(c.normal.fov,size.x,size.y,m.projection.value[0],m.projection.value[5],m.projection.value[8],m.projection.value[9]));
}
void uiAimParts(lemming::aim::Settings& cfg){float s=g_uiScale;auto a=ImGui::GetCursorScreenPos();float half=(ImGui::GetContentRegionAvail().x-10*s)*.5f;for(int i=0;i<8;++i){ImGui::SetCursorScreenPos(ImVec2(a.x+(i%2)*(half+10*s),a.y+(i/2)*52*s));ImGui::PushID(i);if(uiChoiceButton("body",lemming::aim::kBodyNames[i],(cfg.bodies&(1u<<i))!=0,ImVec2(half,44*s)))cfg.bodies^=1u<<i;ImGui::PopID();}ImGui::SetCursorScreenPos(ImVec2(a.x,a.y+216*s));}
void uiAimPriority(lemming::aim::Settings& cfg){float s=g_uiScale;const char* names[]={"FOV","Distance","Low HP"};auto a=ImGui::GetCursorScreenPos();float width=(ImGui::GetContentRegionAvail().x-12*s)/3;for(int i=0;i<3;++i){ImGui::SetCursorScreenPos(ImVec2(a.x+i*(width+6*s),a.y));ImGui::PushID(i);if(uiChoiceButton("priority",names[i],cfg.priority==i,ImVec2(width,44*s)))cfg.priority=i;ImGui::PopID();}ImGui::SetCursorScreenPos(ImVec2(a.x,a.y+52*s));}
void uiAimCoverage(const char* id,lemming::aim::Settings& cfg){float coverage=cfg.fov*2;uiSlider(id,"FOV coverage (360 = all directions)",coverage,1,360,"%.1f deg");cfg.fov=coverage*.5f;}
void renderAimControls(float x,float y,float slide){
 using namespace lemming::aim;float s=g_uiScale;auto* d=ImGui::GetWindowDrawList();uiCard(d,ImVec2(x+30*s,y+124*s),ImVec2(x+395*s,y+570*s));uiCard(d,ImVec2(x+425*s,y+124*s),ImVec2(x+790*s,y+570*s));
 const char* headings[6][2]={{"ANGLE AIM","ASSISTS & FOV DISPLAY"},{"SILENT AIM","MULTI-SELECT HITBOXES"},{"TARGET SELECTION","BODY PARTS"},{"ANGLE MULTIPOINTS","SILENT MULTIPOINTS"},{"TRIGGERBOT","CAMERA & AUTO SCOPE"},{"ANGLE PREDICTION","SILENT PREDICTION"}};for(int i=0;i<2;++i)uiText(d,ImVec2(x+(i?607.5f:212.5f)*s,y+148*s),headings[g_subsection][i],uiColor(ImVec4(.48f,.54f,.66f,1)),13*s,g_uiSmallFont);
 ImGui::SetCursorPos(ImVec2(47*s,176*s+slide));ImGui::BeginChild("##aim_left",ImVec2(331*s,376*s),ImGuiChildFlags_None,ImGuiWindowFlags_NoScrollbar|ImGuiWindowFlags_NoScrollWithMouse);
 if(g_subsection<=1){auto& cfg=g_subsection==0?g_aimUi.normal:g_aimUi.silent;uiToggle(g_subsection==0?"Enable angle aim":"Enable Silent Aim",cfg.enabled);if(g_subsection==0)uiToggle("Only while attacking",cfg.onAttack);uiToggle("Pause while menu is open",g_aimUi.pauseInMenu);uiAimCoverage("aim_fov",cfg);uiSlider("aim_range","Maximum distance",cfg.maxDistance,1,500,"%.0f m");if(g_subsection==0)uiSlider("aim_smooth","Smoothing time",cfg.smoothing,0,1,"%.2f s");
 }else if(g_subsection==2){auto a=ImGui::GetCursorScreenPos();float half=(ImGui::GetContentRegionAvail().x-10*s)*.5f;if(uiChoiceButton("edit_angles","Angles",g_aimEditMode==0,ImVec2(half,44*s)))g_aimEditMode=0;ImGui::SetCursorScreenPos(ImVec2(a.x+half+10*s,a.y));if(uiChoiceButton("edit_silent","Silent",g_aimEditMode==1,ImVec2(half,44*s)))g_aimEditMode=1;ImGui::SetCursorScreenPos(ImVec2(a.x,a.y+64*s));auto& cfg=g_aimEditMode==0?g_aimUi.normal:g_aimUi.silent;uiToggle("Keep current target",cfg.lockTarget);uiAimPriority(cfg);uiAimCoverage("target_fov",cfg);uiSlider("target_range","Maximum distance",cfg.maxDistance,1,500,"%.0f m");
 }else if(g_subsection==5){uiToggle("Angle motion prediction",g_aimUi.normal.prediction);uiSlider("normal_prediction_ms","Extra prediction lead",g_aimUi.normal.predictionMs,0,100,"%.0f ms");ImGui::TextWrapped("Velocity + snapshot age + bounded smoothing compensation. Resets on stale data, world changes and teleports.");}else if(g_subsection==4){auto& cfg=g_aimUi.autoFire;uiToggle("Enable Triggerbot",cfg.enabled);uiSlider("trigger_delay","Trigger delay",cfg.delayMs,0,300,"%.0f ms");uiSlider("trigger_interval","Minimum shot interval",cfg.intervalMs,30,1000,"%.0f ms");uiSlider("trigger_timeout","Cycle timeout",cfg.timeoutMs,200,2000,"%.0f ms");}else{uiToggle("Angle multipoints",g_aimUi.normal.multipoints);uiSlider("normal_point_scale","Point scale",g_aimUi.normal.pointScale,0,.9f,"%.2f");uiAimParts(g_aimUi.normal);}ImGui::EndChild();
 ImGui::SetCursorPos(ImVec2(442*s,176*s+slide));ImGui::BeginChild("##aim_right",ImVec2(331*s,376*s),ImGuiChildFlags_None,ImGuiWindowFlags_NoScrollbar|ImGuiWindowFlags_NoScrollWithMouse);
 if(g_subsection==0){auto& cfg=g_aimUi.normal;uiToggle("Show FOV",cfg.showFov);uiColorRow("FOV color",g_angleFovColor);uiSlider("fov_thickness","FOV thickness",g_angleFovThickness,1,3,"%.1f px");uiToggle("Visible check",cfg.visibleCheck);uiToggle("RCS",cfg.rcs);uiSlider("rcs_strength","RCS strength",cfg.rcsStrength,0,100,"%.0f %%");
  uiTextLeft(d,ImGui::GetCursorScreenPos(),"Body parts: Targeting / Multipoints",uiColor(ImVec4(.48f,.54f,.66f,1)),12*s,g_uiSmallFont);
 }else if(g_subsection==5){uiToggle("Silent motion prediction",g_aimUi.silent.prediction);uiSlider("silent_prediction_ms","Extra prediction lead",g_aimUi.silent.predictionMs,0,100,"%.0f ms");ImGui::TextWrapped("Live hitbox refresh; center-first Head. Extra lead stays within 35%% of the smallest hitbox radius. No guessed latency or bullet speed.");}else if(g_subsection==4){uiToggle("Back camera",g_aimUi.autoFire.returnCamera);uiToggle("Auto scope",g_aimUi.autoFire.autoScope);uiTextLeft(d,ImGui::GetCursorScreenPos(),"Back camera controls its own aim cycle.",uiColor(ImVec4(.48f,.54f,.66f,1)),12*s,g_uiSmallFont);ImGui::Dummy(ImVec2(0,28*s));uiTextLeft(d,ImGui::GetCursorScreenPos(),"Real collider hit required before firing.",uiColor(ImVec4(.48f,.54f,.66f,1)),12*s,g_uiSmallFont);ImGui::Dummy(ImVec2(0,28*s));uiTextLeft(d,ImGui::GetCursorScreenPos(),(g_aimUi.autoFire.autoScope&&!g_autoScopeReady.load()?"Scope unavailable; Trigger/Back independent.":"Scope keeps normal weapon timings."),uiColor(ImVec4(.48f,.54f,.66f,1)),12*s,g_uiSmallFont);}else if(g_subsection==3){uiToggle("Silent multipoints",g_aimUi.silent.multipoints);uiSlider("silent_point_scale","Point scale",g_aimUi.silent.pointScale,0,.9f,"%.2f");uiAimParts(g_aimUi.silent);}else{auto& cfg=g_subsection==1?g_aimUi.silent:(g_aimEditMode==0?g_aimUi.normal:g_aimUi.silent);uiAimParts(cfg);uiToggle("Multipoints",cfg.multipoints);uiSlider("inline_point_scale","Point scale",cfg.pointScale,0,.9f,"%.2f");}ImGui::EndChild();
 bool silent=g_subsection==1||(g_subsection==2&&g_aimEditMode==1);auto& cfg=silent?g_aimUi.silent:g_aimUi.normal;int state=!cfg.enabled?0:((g_aimUi.pauseInMenu&&lemming::aim::g_menuOpen.load())?2:(silent?g_silentState.load():g_normalState.load()));if(cfg.enabled&&state==0)state=1;const char* status=stateText(state);if(!silent&&cfg.enabled&&cfg.visibleCheck&&!g_visibilityReady.load())status="Visibility profile pending / rejected (aim is filtered)";else if(!silent&&cfg.enabled&&cfg.rcs&&!g_rcsReady.load())status="RCS profile pending / rejected (Angles remain active)";if(g_subsection==4)status=!g_aimUi.autoFire.enabled?"Automation disabled":(lemming::aim::g_menuOpen.load()?"Automation paused while menu is open":(!g_inputHookReady.load()||!g_silentHookReady.load()||!g_visibilityReady.load()?(!g_inputHookReady.load()?input_init::reasonText(g_inputInstallReason.load()):"Shot / raycast profiles pending; Angles active"):automation::stageText(static_cast<automation::Stage>(g_autoStage.load()))));if(g_subsection==5)status="Built-in bounded motion prediction; live tracking still needs a phone test";uiText(d,ImVec2(x+410*s,y+602*s),g_subsection==3?"Center + 6 bounded points per hitbox; scale uses the smallest extent.":status,uiColor(ImVec4(.52f,.60f,.73f,1)),15*s,g_uiSmallFont);publish(g_aimUi);
}
