#include "features/aim/runtime.hpp"
#include <cassert>
#include <cstring>
#include <iostream>
#include <limits>
extern "C" int __android_log_print(int,const char*,const char*,...){return 0;}
using namespace lemming::aim;namespace rt=lemming::aim::runtime;
static int calls=0;static void emit(void*,void*,rt::Ray*,std::uint64_t){++calls;}static void tick(void*,rt::ExecuteTime,const void*){++calls;}
static bool near(float a,float b){return std::fabs(a-b)<.001f;}
int main(){Configuration c;assert(!c.normal.enabled&&!c.silent.enabled&&c.pauseInMenu);c.normal.fov=std::numeric_limits<float>::quiet_NaN();c.normal.bodies=0xffffffff;c.normal.pointScale=10;c.normal.priority=99;publish(c);auto clean=configuration();assert(clean.normal.bodies==255&&clean.normal.fov==8&&near(clean.normal.pointScale,.9f)&&clean.normal.priority==2);
assert(bodyForBone(10)==0&&bodyForBone(9)==1&&bodyForBone(54)==2&&bodyForBone(7)==3&&bodyForBone(0)==4&&bodyForBone(13)==5&&bodyForBone(2)==6&&bodyForBone(5)==7&&bodyForBone(999)==-1);
for(Angles a:{Angles{0,0},Angles{25,160},Angles{-80,-178}}){auto b=anglesFor(forwardFor(a));assert(near(a.pitch,b.pitch)&&near(wrap(a.yaw-b.yaw),0));}auto shortest=smooth({0,179},{0,-179},0,1.f/60);assert(near(shortest.yaw,-179));auto split=smooth(smooth({0,0},{0,60},.2f,.01f),{0,60},.2f,.01f);auto once=smooth({0,0},{0,60},.2f,.02f);assert(near(split.yaw,once.yaw));
Settings s;HitVolume head{{0,0,10},{.2f,.3f,.4f},10};std::array<Vec3,7> points{};assert(samples(head,s,points)==1);s.multipoints=true;assert(samples(head,s,points)==7);for(auto p:points){auto d=sub(p,head.center);assert(std::fabs(d.x)<=head.extents.x&&std::fabs(d.y)<=head.extents.y&&std::fabs(d.z)<=head.extents.z);}s.pointScale=0;assert(samples(head,s,points)==1);
Selection best;consider(best,s,1,100,{0,0,0},{0,0,1},head);assert(best.valid&&best.player==1&&best.bone==10);s.bodies=bodyBit(Body::Chest);best={};consider(best,s,1,100,{0,0,0},{0,0,1},head);assert(!best.valid);auto chest=head;chest.bone=8;consider(best,s,2,80,{0,0,0},{0,0,1},chest);assert(best.valid&&best.bone==8);s.bodies=0;best={};consider(best,s,1,100,{0,0,0},{0,0,1},head);assert(!best.valid);s.bodies=255;s.maxDistance=5;consider(best,s,1,100,{0,0,0},{0,0,1},head);assert(!best.valid);s.maxDistance=150;auto side=head;side.center={10,0,0};consider(best,s,1,100,{0,0,0},{0,0,1},side);assert(!best.valid);
s.priority=2;best={};consider(best,s,1,100,{0,0,0},{0,0,1},head);consider(best,s,2,25,{0,0,0},{0,0,1},head);assert(best.player==2);s.lockTarget=true;best={};consider(best,s,1,100,{0,0,0},{0,0,1},head,1);consider(best,s,2,25,{0,0,0},{0,0,1},head,1);assert(best.player==1);
std::atomic<int> status{0};c={};assert(!rt::gate(c,c.normal,status)&&status==0);c.normal.enabled=true;g_menuOpen=true;assert(!rt::gate(c,c.normal,status)&&status==2);g_menuOpen=false;c.normal.bodies=0;assert(!rt::gate(c,c.normal,status)&&status==5);
rt::Ray rays[3]={{{0,0,0},{0,0,1}},{{0,1,0},{1,0,0}},{{1,0,0},{0,1,0}}};assert(rt::stackSpan(rays,3)&&!rt::stackSpan(rays,0)&&!rt::stackSpan(rays,65)&&!rt::stackSpan(reinterpret_cast<rt::Ray*>(1),3));rt::Ray copy[3];std::memcpy(copy,rays,sizeof(rays));rt::g_emitOriginal=&emit;rt::g_functionsValid=false;publish({});rt::emitRays(nullptr,nullptr,rays,3);assert(calls==1&&!std::memcmp(copy,rays,sizeof(rays)));rt::emitRays(nullptr,nullptr,nullptr,0);assert(calls==2);rt::g_cameraOriginal.store(&tick);rt::cameraTick(nullptr,{1,.016f},nullptr);assert(calls==3);
alignas(8) char player[0xa0]{},stats[0x30]{};alignas(8) char classStorage[0x30]{},worldStorage[0x30]{};void* cls=classStorage;void* world=worldStorage;void* st=stats;std::uint16_t hp=80;std::memcpy(player,&cls,8);std::memcpy(player+0x18,&world,8);std::memcpy(player+0x70,&st,8);std::memcpy(stats+0x10,&hp,2);rt::ed::g_runtime.playerClass=cls;auto& actor=rt::g_actors[0];actor={};actor.player=player;actor.world=world;actor.team=2;actor.hp=80;actor.count=1;actor.volumes[0]=head;actor.captured=rt::Clock::now();s={};std::uintptr_t last=0;rt::ed::refreshMaps();auto target=rt::select(s,world,1,{0,0,0},{0,0,1},last);assert(target.valid&&last==reinterpret_cast<std::uintptr_t>(player));actor.team=1;assert(!rt::select(s,world,1,{0,0,0},{0,0,1},last).valid);actor.team=2;assert(!rt::select(s,reinterpret_cast<void*>(3),1,{0,0,0},{0,0,1},last).valid);actor.captured=rt::Clock::now()-std::chrono::seconds(1);assert(!rt::select(s,world,1,{0,0,0},{0,0,1},last).valid);actor.captured=rt::Clock::now();hp=0;std::memcpy(stats+0x10,&hp,2);assert(!rt::select(s,world,1,{0,0,0},{0,0,1},last).valid);
std::cout<<"PASS aim math, multipoints, multi-select, FOV/range/priority/lock, config guards, stale/team/world/dead filters, stack-span checks and original-call passthrough\n";}
